"""initial contribution schema

Revision ID: 6edfedde05d8
Revises: 
Create Date: 2026-10-04 10:47:47.337291
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = '6edfedde05d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('consent_cc0_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_storage_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_version', sa.String(length=16), nullable=False),
    sa.Column('age_band', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('native_languages', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='sentence_status'), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('recording_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lang', 'normalized', name='uq_sentence_lang_normalized')
    )
    op.create_index('ix_sentences_lang_status', 'sentences', ['lang', 'status'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('original_path', sa.String(length=400), nullable=False),
    sa.Column('original_mime', sa.String(length=80), nullable=True),
    sa.Column('wav_path', sa.String(length=400), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('rms', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'validated', 'rejected', 'failed', name='recording_status'), nullable=False),
    sa.Column('reject_reason', sa.String(length=80), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('good_votes', sa.Integer(), nullable=False),
    sa.Column('bad_votes', sa.Integer(), nullable=False),
    sa.Column('client_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recordings_contributor', 'recordings', ['contributor_id'], unique=False)
    op.create_index('ix_recordings_sentence', 'recordings', ['sentence_id'], unique=False)
    op.create_index('ix_recordings_status', 'recordings', ['status'], unique=False)
    op.create_table('validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('good', 'bad', 'skip', name='verdict'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id', 'contributor_id', name='uq_validation_once')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validations')
    op.drop_index('ix_recordings_status', table_name='recordings')
    op.drop_index('ix_recordings_sentence', table_name='recordings')
    op.drop_index('ix_recordings_contributor', table_name='recordings')
    op.drop_table('recordings')
    op.drop_index('ix_sentences_lang_status', table_name='sentences')
    op.drop_table('sentences')
    op.drop_table('contributors')
    # ### end Alembic commands ###
