"""The question bank the bot draws from.

Prompts are written in English and Hindi (the two bridge languages most Gojri and
Pahari speakers read) and answered in the target language, by typing or by voice.
Three kinds:

  question   open prompts ("What did you eat today?") -> spontaneous speech, long answers
  translate  "How do you say: 'It is raining'?"        -> short, controlled sentences
  word       "What do you call 'mother'?"               -> vocabulary, one or two words

`build_bank()` composes the lists below into 1000+ unique prompts. Edit the lists,
re-run `lowres-asr seed-prompts`; upserts are keyed on the English text.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass


@dataclass(frozen=True)
class PromptSpec:
    category: str
    kind: str  # question | translate | word
    en: str
    hi: str


# =========================================================================== questions
# (category, English, Hindi)

QUESTIONS: list[tuple[str, str, str]] = [
    # greetings
    ("greetings", "How do you greet someone in the morning?", "आप सुबह किसी का अभिवादन कैसे करते हैं?"),
    ("greetings", "How do you say goodbye to a friend?", "आप किसी दोस्त को अलविदा कैसे कहते हैं?"),
    ("greetings", "How do you ask someone how they are?", "आप किसी से उसका हाल कैसे पूछते हैं?"),
    ("greetings", "How do you thank someone?", "आप किसी को धन्यवाद कैसे देते हैं?"),
    ("greetings", "How do you welcome a guest into your home?", "आप घर आए मेहमान का स्वागत कैसे करते हैं?"),
    ("greetings", "How do you introduce yourself?", "आप अपना परिचय कैसे देते हैं?"),
    ("greetings", "How do you politely ask for help?", "आप विनम्रता से मदद कैसे माँगते हैं?"),
    ("greetings", "How do you apologise to someone?", "आप किसी से माफ़ी कैसे माँगते हैं?"),
    ("greetings", "How do you congratulate someone?", "आप किसी को बधाई कैसे देते हैं?"),
    ("greetings", "How do you wish someone good luck?", "आप किसी को शुभकामनाएँ कैसे देते हैं?"),
    ("greetings", "What do you say when someone sneezes?", "जब कोई छींकता है तो आप क्या कहते हैं?"),
    ("greetings", "How do you address an elder respectfully?", "आप किसी बुज़ुर्ग को आदर से कैसे संबोधित करते हैं?"),
    # family
    ("family", "Tell me about your family.", "मुझे अपने परिवार के बारे में बताइए।"),
    ("family", "How many brothers and sisters do you have?", "आपके कितने भाई-बहन हैं?"),
    ("family", "What do you call your mother's brother?", "आप अपनी माँ के भाई को क्या कहते हैं?"),
    ("family", "What do you call your father's sister?", "आप अपने पिता की बहन को क्या कहते हैं?"),
    ("family", "Describe your grandmother.", "अपनी दादी या नानी के बारे में बताइए।"),
    ("family", "What does your father do for a living?", "आपके पिता क्या काम करते हैं?"),
    ("family", "Who is the oldest person in your family?", "आपके परिवार में सबसे बुज़ुर्ग कौन हैं?"),
    ("family", "What do you like to do with your family?", "आप अपने परिवार के साथ क्या करना पसंद करते हैं?"),
    ("family", "Tell me about a wedding in your family.", "अपने परिवार की किसी शादी के बारे में बताइए।"),
    ("family", "How do children address their parents?", "बच्चे अपने माता-पिता को कैसे बुलाते हैं?"),
    ("family", "What do you call your husband's or wife's parents?", "आप अपने ससुराल वालों को क्या कहते हैं?"),
    ("family", "Who do you talk to when you are worried?", "जब आप परेशान होते हैं तो किससे बात करते हैं?"),
    # home
    ("home", "Describe your house.", "अपने घर का वर्णन कीजिए।"),
    ("home", "What is the first thing you do in the morning?", "आप सुबह सबसे पहले क्या करते हैं?"),
    ("home", "What do you do before going to sleep?", "सोने से पहले आप क्या करते हैं?"),
    ("home", "Who cooks in your home?", "आपके घर में खाना कौन बनाता है?"),
    ("home", "What is in your kitchen?", "आपकी रसोई में क्या-क्या है?"),
    ("home", "Where do you keep your clothes?", "आप अपने कपड़े कहाँ रखते हैं?"),
    ("home", "How do you keep your house warm in winter?", "सर्दियों में आप घर को गर्म कैसे रखते हैं?"),
    ("home", "What do you see from your window?", "आपकी खिड़की से क्या दिखता है?"),
    ("home", "What is your house made of?", "आपका घर किस चीज़ से बना है?"),
    ("home", "Where do the animals sleep at night?", "रात में जानवर कहाँ सोते हैं?"),
    # food
    ("food", "What did you eat today?", "आज आपने क्या खाया?"),
    ("food", "What is your favourite food?", "आपका पसंदीदा खाना क्या है?"),
    ("food", "How is bread made in your home?", "आपके घर में रोटी कैसे बनती है?"),
    ("food", "Describe a dish that is cooked at weddings.", "शादियों में बनने वाले किसी पकवान के बारे में बताइए।"),
    ("food", "What do you drink in the morning?", "आप सुबह क्या पीते हैं?"),
    ("food", "How do you make tea?", "आप चाय कैसे बनाते हैं?"),
    ("food", "Which vegetables grow near your home?", "आपके घर के पास कौन-सी सब्ज़ियाँ उगती हैं?"),
    ("food", "What do you eat during a festival?", "त्योहार पर आप क्या खाते हैं?"),
    ("food", "What food do you give to a sick person?", "बीमार व्यक्ति को आप क्या खिलाते हैं?"),
    ("food", "How do you store milk and butter?", "आप दूध और मक्खन कैसे रखते हैं?"),
    ("food", "What fruits do you like?", "आपको कौन-से फल पसंद हैं?"),
    ("food", "Tell me how to cook rice.", "मुझे बताइए चावल कैसे पकाते हैं।"),
    ("food", "What do you eat in winter that you do not eat in summer?", "सर्दियों में आप क्या खाते हैं जो गर्मियों में नहीं खाते?"),
    ("food", "How do you make butter or ghee at home?", "घर में मक्खन या घी कैसे बनाते हैं?"),
    # daily life
    ("daily_life", "Describe your typical day.", "अपने एक आम दिन के बारे में बताइए।"),
    ("daily_life", "What time do you wake up?", "आप कितने बजे उठते हैं?"),
    ("daily_life", "What did you do yesterday?", "कल आपने क्या किया?"),
    ("daily_life", "What will you do tomorrow?", "कल आप क्या करेंगे?"),
    ("daily_life", "How do you spend your evenings?", "आप अपनी शाम कैसे बिताते हैं?"),
    ("daily_life", "What do you do on a holiday?", "छुट्टी के दिन आप क्या करते हैं?"),
    ("daily_life", "How do you fetch water?", "आप पानी कैसे लाते हैं?"),
    ("daily_life", "How do you wash clothes?", "आप कपड़े कैसे धोते हैं?"),
    ("daily_life", "What games do children play in your area?", "आपके इलाके में बच्चे कौन-से खेल खेलते हैं?"),
    ("daily_life", "What do you do when you cannot sleep?", "जब आपको नींद नहीं आती तो आप क्या करते हैं?"),
    ("daily_life", "What do you do when guests arrive unexpectedly?", "जब अचानक मेहमान आ जाते हैं तो आप क्या करते हैं?"),
    ("daily_life", "What is the most tiring work you do?", "आपका सबसे थका देने वाला काम कौन-सा है?"),
    # village
    ("village", "Describe your village or town.", "अपने गाँव या शहर का वर्णन कीजिए।"),
    ("village", "What is the name of your village and what does it mean?", "आपके गाँव का नाम क्या है और उसका क्या मतलब है?"),
    ("village", "How far is the nearest market?", "सबसे नज़दीकी बाज़ार कितनी दूर है?"),
    ("village", "What do people in your village do for work?", "आपके गाँव में लोग क्या काम करते हैं?"),
    ("village", "Is there a river or stream near your home?", "क्या आपके घर के पास कोई नदी या नाला है?"),
    ("village", "How has your village changed since you were a child?", "बचपन से अब तक आपका गाँव कैसे बदला है?"),
    ("village", "Describe the road to your village.", "अपने गाँव तक जाने वाली सड़क के बारे में बताइए।"),
    ("village", "Who do people go to when they have a problem?", "जब लोगों को कोई समस्या होती है तो वे किसके पास जाते हैं?"),
    ("village", "Where do people gather in the evening?", "शाम को लोग कहाँ इकट्ठा होते हैं?"),
    ("village", "Tell me about a well-known person from your village.", "अपने गाँव के किसी जाने-माने व्यक्ति के बारे में बताइए।"),
    # farming
    ("farming", "What crops are grown in your area?", "आपके इलाके में कौन-सी फ़सलें उगाई जाती हैं?"),
    ("farming", "How do you prepare the field for sowing?", "बुवाई के लिए खेत कैसे तैयार करते हैं?"),
    ("farming", "When is the harvest season?", "कटाई का मौसम कब होता है?"),
    ("farming", "How do you water the fields?", "आप खेतों में पानी कैसे देते हैं?"),
    ("farming", "What tools do farmers use?", "किसान कौन-से औज़ार इस्तेमाल करते हैं?"),
    ("farming", "Tell me about taking animals to graze.", "जानवरों को चराने ले जाने के बारे में बताइए।"),
    ("farming", "How do you make hay for winter?", "सर्दियों के लिए सूखी घास कैसे बनाते हैं?"),
    ("farming", "What do you do when there is no rain?", "जब बारिश नहीं होती तो आप क्या करते हैं?"),
    ("farming", "How do you move with your herds in summer?", "गर्मियों में आप अपने रेवड़ के साथ कैसे चलते हैं?"),
    ("farming", "What do you grow in your kitchen garden?", "आप अपनी बाड़ी में क्या उगाते हैं?"),
    # animals
    ("animals", "Which animals do people keep at home?", "लोग घर में कौन-से जानवर पालते हैं?"),
    ("animals", "Describe your cow or buffalo.", "अपनी गाय या भैंस के बारे में बताइए।"),
    ("animals", "How do you call your goats back home?", "आप अपनी बकरियों को घर वापस कैसे बुलाते हैं?"),
    ("animals", "What wild animals live in the hills near you?", "आपके पास की पहाड़ियों में कौन-से जंगली जानवर रहते हैं?"),
    ("animals", "What birds do you see in the morning?", "सुबह आप कौन-से पक्षी देखते हैं?"),
    ("animals", "Tell me about a dog you have known.", "किसी कुत्ते के बारे में बताइए जिसे आप जानते थे।"),
    ("animals", "How do you milk a cow?", "गाय का दूध कैसे निकालते हैं?"),
    ("animals", "What sound does a rooster make in your language?", "आपकी भाषा में मुर्गा कैसे बोलता है?"),
    ("animals", "What do you call a baby goat, a baby cow and a baby horse?", "बकरी, गाय और घोड़े के बच्चे को आप क्या कहते हैं?"),
    ("animals", "Which animal is the most useful to your family?", "आपके परिवार के लिए कौन-सा जानवर सबसे उपयोगी है?"),
    # weather
    ("weather", "How is the weather today?", "आज मौसम कैसा है?"),
    ("weather", "Describe winter in your area.", "अपने इलाके की सर्दी के बारे में बताइए।"),
    ("weather", "What do you do when it snows?", "जब बर्फ़ गिरती है तो आप क्या करते हैं?"),
    ("weather", "Tell me about the monsoon rains.", "बरसात के मौसम के बारे में बताइए।"),
    ("weather", "Which season do you like most and why?", "आपको कौन-सा मौसम सबसे ज़्यादा पसंद है और क्यों?"),
    ("weather", "How do you know a storm is coming?", "आपको कैसे पता चलता है कि तूफ़ान आने वाला है?"),
    ("weather", "What is summer like where you live?", "जहाँ आप रहते हैं वहाँ गर्मी कैसी होती है?"),
    ("weather", "Describe the coldest night you remember.", "सबसे ठंडी रात के बारे में बताइए जो आपको याद हो।"),
    # festivals
    ("festivals", "Which festival do you enjoy the most?", "आपको कौन-सा त्योहार सबसे ज़्यादा पसंद है?"),
    ("festivals", "How do you celebrate Eid or Diwali?", "आप ईद या दिवाली कैसे मनाते हैं?"),
    ("festivals", "What happens at a wedding in your community?", "आपके समाज में शादी में क्या-क्या होता है?"),
    ("festivals", "Tell me about a fair or mela you have been to.", "किसी मेले के बारे में बताइए जहाँ आप गए हों।"),
    ("festivals", "What songs are sung at weddings?", "शादियों में कौन-से गीत गाए जाते हैं?"),
    ("festivals", "How do you celebrate the birth of a child?", "बच्चे के जन्म का जश्न आप कैसे मनाते हैं?"),
    ("festivals", "What do you wear on special occasions?", "ख़ास मौकों पर आप क्या पहनते हैं?"),
    ("festivals", "Tell me about a dance from your region.", "अपने क्षेत्र के किसी नृत्य के बारे में बताइए।"),
    ("festivals", "What happens on the first day of spring?", "वसंत के पहले दिन क्या होता है?"),
    ("festivals", "How do you mourn when someone dies?", "जब कोई गुज़र जाता है तो आप शोक कैसे मनाते हैं?"),
    # childhood
    ("childhood", "Tell me about your childhood.", "अपने बचपन के बारे में बताइए।"),
    ("childhood", "What was your favourite game as a child?", "बचपन में आपका पसंदीदा खेल क्या था?"),
    ("childhood", "Who was your best friend when you were small?", "जब आप छोटे थे तो आपका सबसे अच्छा दोस्त कौन था?"),
    ("childhood", "What stories did your grandparents tell you?", "आपके दादा-दादी या नाना-नानी आपको कौन-सी कहानियाँ सुनाते थे?"),
    ("childhood", "What did you want to become when you grew up?", "बड़े होकर आप क्या बनना चाहते थे?"),
    ("childhood", "Describe your first day at school.", "स्कूल के अपने पहले दिन के बारे में बताइए।"),
    ("childhood", "What did you get into trouble for as a child?", "बचपन में आपको किस बात पर डाँट पड़ती थी?"),
    ("childhood", "Recite a children's rhyme you remember.", "कोई बच्चों की कविता सुनाइए जो आपको याद हो।"),
    ("childhood", "What did your mother sing to you?", "आपकी माँ आपको क्या गाकर सुनाती थीं?"),
    ("childhood", "What was your favourite place to play?", "खेलने की आपकी पसंदीदा जगह कौन-सी थी?"),
    # work
    ("work", "What work do you do?", "आप क्या काम करते हैं?"),
    ("work", "Describe a hard day at work.", "काम के किसी मुश्किल दिन के बारे में बताइए।"),
    ("work", "What did you learn from your first job?", "अपनी पहली नौकरी से आपने क्या सीखा?"),
    ("work", "What skill would you like to learn?", "आप कौन-सा हुनर सीखना चाहेंगे?"),
    ("work", "Who taught you your trade?", "आपको आपका काम किसने सिखाया?"),
    ("work", "What do women in your village do for work?", "आपके गाँव की महिलाएँ क्या काम करती हैं?"),
    ("work", "Do young people leave the village for work? Why?", "क्या युवा काम के लिए गाँव छोड़ते हैं? क्यों?"),
    ("work", "How do you earn money in winter?", "सर्दियों में आप पैसे कैसे कमाते हैं?"),
    # travel
    ("travel", "Have you ever travelled to a big city? Tell me about it.", "क्या आप कभी किसी बड़े शहर गए हैं? उसके बारे में बताइए।"),
    ("travel", "How do you get from your home to the nearest town?", "आप अपने घर से नज़दीकी कस्बे तक कैसे जाते हैं?"),
    ("travel", "Describe a long journey you remember.", "किसी लंबी यात्रा के बारे में बताइए जो आपको याद हो।"),
    ("travel", "Where would you like to go if you could travel anywhere?", "अगर आप कहीं भी जा सकते तो कहाँ जाना चाहेंगे?"),
    ("travel", "How do you ask for directions?", "आप रास्ता कैसे पूछते हैं?"),
    ("travel", "Tell me about walking in the mountains.", "पहाड़ों में पैदल चलने के बारे में बताइए।"),
    ("travel", "What do you take with you on a journey?", "यात्रा पर आप अपने साथ क्या ले जाते हैं?"),
    ("travel", "Describe the bus ride to the city.", "शहर तक की बस यात्रा के बारे में बताइए।"),
    # health
    ("health", "What do you do when you have a cold?", "जब आपको ज़ुकाम होता है तो आप क्या करते हैं?"),
    ("health", "Which herbs are used as medicine in your area?", "आपके इलाके में कौन-सी जड़ी-बूटियाँ दवा के रूप में इस्तेमाल होती हैं?"),
    ("health", "How far is the nearest doctor or hospital?", "सबसे नज़दीकी डॉक्टर या अस्पताल कितनी दूर है?"),
    ("health", "How do you take care of a small child who is ill?", "बीमार छोटे बच्चे की देखभाल आप कैसे करते हैं?"),
    ("health", "What do you do to stay healthy?", "स्वस्थ रहने के लिए आप क्या करते हैं?"),
    ("health", "Describe how you feel when you are tired.", "बताइए जब आप थके होते हैं तो कैसा महसूस करते हैं।"),
    ("health", "How do you treat a cut or a wound at home?", "घर पर चोट या घाव का इलाज कैसे करते हैं?"),
    ("health", "What do you tell a child who has a toothache?", "दाँत दर्द वाले बच्चे से आप क्या कहते हैं?"),
    # nature
    ("nature", "Describe the mountains near your home.", "अपने घर के पास के पहाड़ों का वर्णन कीजिए।"),
    ("nature", "What trees grow around your village?", "आपके गाँव के आसपास कौन-से पेड़ उगते हैं?"),
    ("nature", "Tell me about a spring or stream where you get water.", "किसी झरने या नाले के बारे में बताइए जहाँ से आप पानी लेते हैं।"),
    ("nature", "What flowers bloom in spring?", "वसंत में कौन-से फूल खिलते हैं?"),
    ("nature", "What does the sky look like at night in your village?", "आपके गाँव में रात का आसमान कैसा दिखता है?"),
    ("nature", "Describe the sound of rain on your roof.", "अपनी छत पर बारिश की आवाज़ का वर्णन कीजिए।"),
    ("nature", "What happens in the forest in autumn?", "पतझड़ में जंगल में क्या होता है?"),
    ("nature", "Which wild fruits or nuts do you collect?", "आप कौन-से जंगली फल या मेवे इकट्ठा करते हैं?"),
    # stories
    ("stories", "Tell me a short story you know.", "कोई छोटी कहानी सुनाइए जो आप जानते हों।"),
    ("stories", "Tell me a proverb in your language and what it means.", "अपनी भाषा की कोई कहावत और उसका मतलब बताइए।"),
    ("stories", "Tell me a joke.", "कोई चुटकुला सुनाइए।"),
    ("stories", "Tell me about a brave person from your area.", "अपने इलाके के किसी बहादुर व्यक्ति के बारे में बताइए।"),
    ("stories", "Tell me a story about a clever animal.", "किसी चालाक जानवर की कहानी सुनाइए।"),
    ("stories", "What is a saying your mother often used?", "आपकी माँ अक्सर कौन-सी कहावत कहती थीं?"),
    ("stories", "Describe a dream you remember.", "कोई सपना बताइए जो आपको याद हो।"),
    ("stories", "Tell me about the happiest day of your life.", "अपनी ज़िंदगी के सबसे ख़ुशी के दिन के बारे में बताइए।"),
    ("stories", "Tell me a riddle.", "कोई पहेली सुनाइए।"),
    ("stories", "Tell me about a time you were very scared.", "किसी ऐसे समय के बारे में बताइए जब आप बहुत डर गए थे।"),
    ("stories", "Describe a folk song from your area.", "अपने इलाके के किसी लोकगीत के बारे में बताइए।"),
    # opinions
    ("opinions", "What do you like most about your language?", "आपको अपनी भाषा में सबसे अच्छा क्या लगता है?"),
    ("opinions", "Why is it important for children to learn your language?", "बच्चों के लिए आपकी भाषा सीखना क्यों ज़रूरी है?"),
    ("opinions", "What would make life in your village better?", "आपके गाँव का जीवन बेहतर कैसे हो सकता है?"),
    ("opinions", "What advice would you give to a young person?", "आप किसी युवा को क्या सलाह देंगे?"),
    ("opinions", "What makes you happy?", "आपको किस चीज़ से ख़ुशी मिलती है?"),
    ("opinions", "What are you afraid of?", "आपको किस चीज़ से डर लगता है?"),
    ("opinions", "What do you think about mobile phones?", "मोबाइल फ़ोन के बारे में आप क्या सोचते हैं?"),
    ("opinions", "What is the most beautiful place you have seen?", "आपने जो सबसे सुंदर जगह देखी है वह कौन-सी है?"),
    ("opinions", "What is more important, money or family?", "ज़्यादा ज़रूरी क्या है, पैसा या परिवार?"),
    ("opinions", "What do you hope for your children?", "आप अपने बच्चों के लिए क्या उम्मीद रखते हैं?"),
    # language
    ("language", "Count from one to ten.", "एक से दस तक गिनती बोलिए।"),
    ("language", "Count from ten to twenty.", "दस से बीस तक गिनती बोलिए।"),
    ("language", "Say the days of the week.", "हफ़्ते के दिनों के नाम बोलिए।"),
    ("language", "Name the months or seasons as your elders say them.", "महीनों या मौसमों के नाम बताइए जैसे आपके बड़े कहते हैं।"),
    ("language", "What are the colours you can name?", "आप कौन-कौन से रंगों के नाम बता सकते हैं?"),
    ("language", "Say a sentence with the word for 'water' in it.", "'पानी' शब्द वाला एक वाक्य बोलिए।"),
    ("language", "What do you call the different times of the day?", "दिन के अलग-अलग समय को आप क्या कहते हैं?"),
    ("language", "How do you say 'I love you' to a child?", "आप किसी बच्चे से 'मैं तुमसे प्यार करता हूँ' कैसे कहते हैं?"),
    ("language", "What is a word in your language that has no Hindi or English equivalent?", "आपकी भाषा का कोई ऐसा शब्द बताइए जिसका हिंदी या अंग्रेज़ी में कोई मतलब न हो।"),
    ("language", "Name the parts of the body from head to toe.", "सिर से पैर तक शरीर के अंगों के नाम बताइए।"),
    ("language", "How do old people speak differently from young people?", "बुज़ुर्ग लोग युवाओं से अलग कैसे बोलते हैं?"),
    ("language", "Name five animals.", "पाँच जानवरों के नाम बताइए।"),
    ("language", "Name five things in your kitchen.", "अपनी रसोई की पाँच चीज़ों के नाम बताइए।"),
    ("language", "Say a sentence about the weather.", "मौसम के बारे में एक वाक्य बोलिए।"),
    ("language", "Say a sentence about your mother.", "अपनी माँ के बारे में एक वाक्य बोलिए।"),
    ("language", "How do you scold a child gently?", "आप किसी बच्चे को प्यार से कैसे डाँटते हैं?"),
    ("language", "What do you say to calm a crying baby?", "रोते हुए बच्चे को चुप कराने के लिए आप क्या कहते हैं?"),
    # market
    ("market", "How do you bargain for a good price?", "आप अच्छे दाम के लिए मोल-भाव कैसे करते हैं?"),
    ("market", "What do you buy at the market every week?", "आप हर हफ़्ते बाज़ार से क्या ख़रीदते हैं?"),
    ("market", "How do you ask the price of something?", "आप किसी चीज़ का दाम कैसे पूछते हैं?"),
    ("market", "Describe the market on a busy day.", "भीड़ वाले दिन बाज़ार का वर्णन कीजिए।"),
    ("market", "What do you sell, if anything?", "आप क्या बेचते हैं, अगर कुछ बेचते हैं तो?"),
    ("market", "What was cheap when you were young and is expensive now?", "आपके बचपन में क्या सस्ता था जो अब महँगा है?"),
    # school
    ("school", "Did you go to school? Tell me about it.", "क्या आप स्कूल गए थे? उसके बारे में बताइए।"),
    ("school", "What was your favourite subject?", "आपका पसंदीदा विषय क्या था?"),
    ("school", "Which language was used in your school?", "आपके स्कूल में कौन-सी भाषा इस्तेमाल होती थी?"),
    ("school", "Describe a teacher you remember.", "किसी शिक्षक के बारे में बताइए जो आपको याद हों।"),
    ("school", "How do children in your village get to school?", "आपके गाँव के बच्चे स्कूल कैसे जाते हैं?"),
    ("school", "What should children learn that school does not teach?", "बच्चों को क्या सीखना चाहिए जो स्कूल नहीं सिखाता?"),
]

# ==================================================================== translate: sentences
# (category, English, Hindi). Short, concrete, everyday. These produce the controlled
# read-style data; answers that pass the sentence rules also join the read-aloud pool.

SENTENCES: list[tuple[str, str, str]] = [
    ("everyday", "I am going home.", "मैं घर जा रहा हूँ।"),
    ("everyday", "Where are you going?", "तुम कहाँ जा रहे हो?"),
    ("everyday", "Come here.", "यहाँ आओ।"),
    ("everyday", "Sit down, please.", "कृपया बैठ जाइए।"),
    ("everyday", "I am very hungry.", "मुझे बहुत भूख लगी है।"),
    ("everyday", "I am thirsty.", "मुझे प्यास लगी है।"),
    ("everyday", "Give me some water.", "मुझे थोड़ा पानी दो।"),
    ("everyday", "The food is ready.", "खाना तैयार है।"),
    ("everyday", "It is time to eat.", "खाने का समय हो गया है।"),
    ("everyday", "I am tired today.", "मैं आज थका हुआ हूँ।"),
    ("everyday", "Wake up, it is morning.", "उठो, सुबह हो गई है।"),
    ("everyday", "Go to sleep now.", "अब सो जाओ।"),
    ("everyday", "Close the door.", "दरवाज़ा बंद करो।"),
    ("everyday", "Open the window.", "खिड़की खोलो।"),
    ("everyday", "Turn off the light.", "बत्ती बुझा दो।"),
    ("everyday", "Where is my phone?", "मेरा फ़ोन कहाँ है?"),
    ("everyday", "I cannot find my keys.", "मुझे अपनी चाबियाँ नहीं मिल रहीं।"),
    ("everyday", "Wait for me.", "मेरा इंतज़ार करो।"),
    ("everyday", "I will come back soon.", "मैं जल्दी वापस आऊँगा।"),
    ("everyday", "Don't be late.", "देर मत करना।"),
    ("everyday", "Let's go together.", "चलो साथ चलते हैं।"),
    ("everyday", "Hurry up!", "जल्दी करो!"),
    ("everyday", "Slow down.", "धीरे चलो।"),
    ("everyday", "Be careful.", "सावधान रहो।"),
    ("everyday", "I don't know.", "मुझे नहीं पता।"),
    ("everyday", "I understand.", "मैं समझ गया।"),
    ("everyday", "I don't understand.", "मुझे समझ नहीं आया।"),
    ("everyday", "Please say that again.", "कृपया फिर से कहिए।"),
    ("everyday", "Speak slowly.", "धीरे बोलिए।"),
    ("everyday", "What is your name?", "आपका नाम क्या है?"),
    ("everyday", "My name is Ali.", "मेरा नाम अली है।"),
    ("everyday", "Where do you live?", "आप कहाँ रहते हैं?"),
    ("everyday", "I live in the village.", "मैं गाँव में रहता हूँ।"),
    ("everyday", "How old are you?", "आपकी उम्र कितनी है?"),
    ("everyday", "I am twenty years old.", "मैं बीस साल का हूँ।"),
    ("everyday", "Do you have children?", "क्या आपके बच्चे हैं?"),
    ("everyday", "I have two sons and a daughter.", "मेरे दो बेटे और एक बेटी है।"),
    ("everyday", "Where is your father?", "आपके पिता कहाँ हैं?"),
    ("everyday", "He has gone to the fields.", "वह खेतों में गए हैं।"),
    ("everyday", "Mother is cooking.", "माँ खाना बना रही हैं।"),
    ("everyday", "The children are playing outside.", "बच्चे बाहर खेल रहे हैं।"),
    ("everyday", "My brother is older than me.", "मेरा भाई मुझसे बड़ा है।"),
    ("everyday", "My sister lives in the city.", "मेरी बहन शहर में रहती है।"),
    ("everyday", "Grandfather is sleeping.", "दादा जी सो रहे हैं।"),
    ("everyday", "We are going to the wedding.", "हम शादी में जा रहे हैं।"),
    ("everyday", "Who is knocking at the door?", "दरवाज़ा कौन खटखटा रहा है?"),
    ("everyday", "Sit here next to me.", "यहाँ मेरे पास बैठो।"),
    ("everyday", "Don't touch that.", "उसे मत छुओ।"),
    ("everyday", "Bring me a chair.", "मेरे लिए कुर्सी लाओ।"),
    ("everyday", "I will do it myself.", "मैं ख़ुद कर लूँगा।"),
    ("feelings", "I am happy today.", "मैं आज ख़ुश हूँ।"),
    ("feelings", "She is sad.", "वह उदास है।"),
    ("feelings", "Why are you angry?", "तुम ग़ुस्सा क्यों हो?"),
    ("feelings", "Don't be afraid.", "डरो मत।"),
    ("feelings", "I miss my home.", "मुझे अपने घर की याद आती है।"),
    ("feelings", "I like this place.", "मुझे यह जगह पसंद है।"),
    ("feelings", "I don't like cold weather.", "मुझे ठंडा मौसम पसंद नहीं है।"),
    ("feelings", "That is a good idea.", "यह अच्छा विचार है।"),
    ("feelings", "I am sorry.", "मुझे माफ़ कर दो।"),
    ("feelings", "Thank you very much.", "बहुत-बहुत धन्यवाद।"),
    ("feelings", "You are welcome.", "कोई बात नहीं।"),
    ("feelings", "I am worried about him.", "मुझे उसकी चिंता है।"),
    ("feelings", "Everything will be fine.", "सब ठीक हो जाएगा।"),
    ("feelings", "I am proud of you.", "मुझे तुम पर गर्व है।"),
    ("feelings", "We laughed a lot.", "हम बहुत हँसे।"),
    ("feelings", "He is a kind man.", "वह दयालु आदमी है।"),
    ("feelings", "I trust you.", "मुझे तुम पर भरोसा है।"),
    ("time", "What time is it?", "कितने बजे हैं?"),
    ("time", "It is five o'clock.", "पाँच बजे हैं।"),
    ("time", "I will come tomorrow morning.", "मैं कल सुबह आऊँगा।"),
    ("time", "He came yesterday evening.", "वह कल शाम आया था।"),
    ("time", "We meet every Sunday.", "हम हर रविवार मिलते हैं।"),
    ("time", "It is getting late.", "देर हो रही है।"),
    ("time", "The sun is setting.", "सूरज डूब रहा है।"),
    ("time", "It is still early.", "अभी जल्दी है।"),
    ("time", "Last year there was a lot of snow.", "पिछले साल बहुत बर्फ़ पड़ी थी।"),
    ("time", "Next week is the festival.", "अगले हफ़्ते त्योहार है।"),
    ("time", "I have been waiting for an hour.", "मैं एक घंटे से इंतज़ार कर रहा हूँ।"),
    ("time", "Come after lunch.", "दोपहर के खाने के बाद आना।"),
    ("time", "The bus leaves at eight.", "बस आठ बजे निकलती है।"),
    ("time", "We will meet again next month.", "हम अगले महीने फिर मिलेंगे।"),
    ("directions", "Where is the market?", "बाज़ार कहाँ है?"),
    ("directions", "Go straight and turn left.", "सीधे जाओ और बाएँ मुड़ो।"),
    ("directions", "The school is on the right.", "स्कूल दाईं तरफ़ है।"),
    ("directions", "It is very far from here.", "यह यहाँ से बहुत दूर है।"),
    ("directions", "The shop is near the mosque.", "दुकान मस्जिद के पास है।"),
    ("directions", "The river is behind the hill.", "नदी पहाड़ी के पीछे है।"),
    ("directions", "How do I get to the bus stop?", "बस अड्डे तक कैसे जाऊँ?"),
    ("directions", "Is this the road to the city?", "क्या यह शहर की सड़क है?"),
    ("directions", "The path goes up the mountain.", "रास्ता पहाड़ के ऊपर जाता है।"),
    ("directions", "Cross the bridge.", "पुल पार करो।"),
    ("directions", "My house is at the top of the hill.", "मेरा घर पहाड़ी के ऊपर है।"),
    ("directions", "Walk along the stream.", "नाले के किनारे-किनारे चलो।"),
    ("weather", "It is raining.", "बारिश हो रही है।"),
    ("weather", "It is very cold today.", "आज बहुत ठंड है।"),
    ("weather", "The sun is very hot.", "धूप बहुत तेज़ है।"),
    ("weather", "It snowed last night.", "कल रात बर्फ़ गिरी।"),
    ("weather", "The wind is blowing hard.", "तेज़ हवा चल रही है।"),
    ("weather", "There are clouds in the sky.", "आसमान में बादल हैं।"),
    ("weather", "Take an umbrella.", "छाता ले लो।"),
    ("weather", "The road is wet.", "सड़क गीली है।"),
    ("weather", "The fog is thick this morning.", "आज सुबह घना कोहरा है।"),
    ("weather", "Spring has come.", "वसंत आ गया है।"),
    ("food", "The tea is hot.", "चाय गर्म है।"),
    ("food", "This bread is fresh.", "यह रोटी ताज़ा है।"),
    ("food", "Do you want more rice?", "क्या तुम्हें और चावल चाहिए?"),
    ("food", "The milk has gone sour.", "दूध खट्टा हो गया है।"),
    ("food", "Put salt in the food.", "खाने में नमक डालो।"),
    ("food", "The mangoes are sweet.", "आम मीठे हैं।"),
    ("food", "Wash the vegetables.", "सब्ज़ियाँ धो लो।"),
    ("food", "The fire has gone out.", "आग बुझ गई है।"),
    ("food", "Bring firewood.", "लकड़ी लाओ।"),
    ("food", "The pot is on the stove.", "बर्तन चूल्हे पर है।"),
    ("food", "The food is too spicy.", "खाना बहुत तीखा है।"),
    ("food", "We eat together in the evening.", "हम शाम को साथ खाते हैं।"),
    ("farming", "The cow is grazing.", "गाय चर रही है।"),
    ("farming", "The goats have run away.", "बकरियाँ भाग गई हैं।"),
    ("farming", "The dog is barking.", "कुत्ता भौंक रहा है।"),
    ("farming", "The wheat is ripe.", "गेहूँ पक गया है।"),
    ("farming", "We will cut the grass tomorrow.", "हम कल घास काटेंगे।"),
    ("farming", "The hen laid an egg.", "मुर्गी ने अंडा दिया।"),
    ("farming", "Tie the buffalo.", "भैंस को बाँध दो।"),
    ("farming", "The field needs water.", "खेत को पानी चाहिए।"),
    ("farming", "Birds are eating the corn.", "चिड़ियाँ मक्का खा रही हैं।"),
    ("farming", "The horse is fast.", "घोड़ा तेज़ है।"),
    ("farming", "The sheep are on the hill.", "भेड़ें पहाड़ी पर हैं।"),
    ("farming", "The harvest was good this year.", "इस साल फ़सल अच्छी हुई।"),
    ("health", "I have a headache.", "मेरे सिर में दर्द है।"),
    ("health", "My stomach hurts.", "मेरे पेट में दर्द है।"),
    ("health", "He has a fever.", "उसे बुखार है।"),
    ("health", "Call the doctor.", "डॉक्टर को बुलाओ।"),
    ("health", "Take this medicine.", "यह दवा लो।"),
    ("health", "Rest for two days.", "दो दिन आराम करो।"),
    ("health", "I feel better now.", "अब मैं बेहतर महसूस कर रहा हूँ।"),
    ("health", "Grandmother cannot see well.", "दादी को ठीक से दिखाई नहीं देता।"),
    ("health", "Drink warm water.", "गर्म पानी पियो।"),
    ("health", "The baby is crying.", "बच्चा रो रहा है।"),
    ("market", "How much does this cost?", "यह कितने का है?"),
    ("market", "It is too expensive.", "यह बहुत महँगा है।"),
    ("market", "Give me a kilo of onions.", "मुझे एक किलो प्याज़ दो।"),
    ("market", "Do you have fresh milk?", "क्या आपके पास ताज़ा दूध है?"),
    ("market", "I will pay tomorrow.", "मैं कल पैसे दूँगा।"),
    ("market", "The shop is closed.", "दुकान बंद है।"),
    ("market", "Here is your change.", "यह रहे आपके बाक़ी पैसे।"),
    ("market", "I want to buy a shawl.", "मैं एक शॉल ख़रीदना चाहता हूँ।"),
    ("market", "Make it a little cheaper.", "थोड़ा सस्ता कर दो।"),
    ("market", "These apples are from our orchard.", "ये सेब हमारे बाग़ के हैं।"),
    ("school", "The children have gone to school.", "बच्चे स्कूल गए हैं।"),
    ("school", "The teacher is strict.", "शिक्षक सख़्त हैं।"),
    ("school", "Read this book.", "यह किताब पढ़ो।"),
    ("school", "Write your name here.", "यहाँ अपना नाम लिखो।"),
    ("work", "I have a lot of work today.", "आज मेरे पास बहुत काम है।"),
    ("work", "He is building a house.", "वह घर बना रहा है।"),
    ("work", "She sews clothes.", "वह कपड़े सिलती है।"),
    ("work", "The shopkeeper is honest.", "दुकानदार ईमानदार है।"),
    ("work", "My son works in the city.", "मेरा बेटा शहर में काम करता है।"),
    ("work", "She sends money home every month.", "वह हर महीने घर पैसे भेजती है।"),
    ("work", "We built this house ourselves.", "यह घर हमने ख़ुद बनाया है।"),
    ("stories", "The old man told us a story.", "बूढ़े आदमी ने हमें एक कहानी सुनाई।"),
    ("stories", "The moon is bright tonight.", "आज रात चाँद चमक रहा है।"),
    ("stories", "The children are singing.", "बच्चे गा रहे हैं।"),
    ("stories", "We danced all night.", "हम पूरी रात नाचे।"),
    ("stories", "The bride is wearing red.", "दुल्हन ने लाल कपड़े पहने हैं।"),
    ("stories", "Everyone came to the fair.", "सब लोग मेले में आए।"),
    ("nature", "The mountain is covered with snow.", "पहाड़ बर्फ़ से ढका है।"),
    ("nature", "The water in the stream is cold.", "नाले का पानी ठंडा है।"),
    ("nature", "The trees have new leaves.", "पेड़ों पर नए पत्ते आ गए हैं।"),
    ("nature", "The road was closed because of the landslide.", "भूस्खलन की वजह से सड़क बंद थी।"),
    ("nature", "There is no electricity today.", "आज बिजली नहीं है।"),
    ("nature", "The phone has no signal here.", "यहाँ फ़ोन में सिग्नल नहीं है।"),
    ("nature", "The stars are very bright tonight.", "आज रात तारे बहुत चमक रहे हैं।"),
    ("nature", "A bird is sitting on the tree.", "एक चिड़िया पेड़ पर बैठी है।"),
]

# ============================================================================ word lists
# category -> [(English, Hindi)]

WORDS: dict[str, list[tuple[str, str]]] = {
    "family": [
        ("mother", "माँ"), ("father", "पिता"), ("brother", "भाई"), ("sister", "बहन"), ("son", "बेटा"),
        ("daughter", "बेटी"), ("husband", "पति"), ("wife", "पत्नी"), ("grandfather (father's side)", "दादा"),
        ("grandmother (father's side)", "दादी"), ("grandfather (mother's side)", "नाना"),
        ("grandmother (mother's side)", "नानी"), ("father's brother", "चाचा"), ("father's brother's wife", "चाची"),
        ("mother's brother", "मामा"), ("mother's sister", "मौसी"), ("nephew", "भतीजा"), ("niece", "भतीजी"),
        ("son-in-law", "दामाद"), ("daughter-in-law", "बहू"), ("bride", "दुल्हन"), ("groom", "दूल्हा"),
        ("child", "बच्चा"), ("baby", "शिशु"), ("friend", "दोस्त"), ("neighbour", "पड़ोसी"), ("guest", "मेहमान"),
        ("old man", "बूढ़ा आदमी"), ("old woman", "बूढ़ी औरत"), ("boy", "लड़का"), ("girl", "लड़की"), ("man", "आदमी"),
        ("woman", "औरत"), ("people", "लोग"), ("twins", "जुड़वाँ"), ("orphan", "अनाथ"), ("widow", "विधवा"),
    ],
    "body": [
        ("head", "सिर"), ("hair", "बाल"), ("face", "चेहरा"), ("eye", "आँख"), ("ear", "कान"), ("nose", "नाक"),
        ("mouth", "मुँह"), ("tooth", "दाँत"), ("tongue", "जीभ"), ("lip", "होंठ"), ("neck", "गर्दन"),
        ("shoulder", "कंधा"), ("arm", "बाँह"), ("hand", "हाथ"), ("finger", "उँगली"), ("nail", "नाख़ून"),
        ("chest", "छाती"), ("back (of body)", "पीठ"), ("stomach", "पेट"), ("leg", "टाँग"), ("knee", "घुटना"),
        ("foot", "पैर"), ("heel", "एड़ी"), ("heart", "दिल"), ("blood", "ख़ून"), ("bone", "हड्डी"), ("skin", "त्वचा"),
        ("beard", "दाढ़ी"), ("forehead", "माथा"), ("elbow", "कोहनी"), ("cheek", "गाल"), ("eyebrow", "भौंह"),
        ("throat", "गला"), ("waist", "कमर"), ("thumb", "अँगूठा"), ("tear", "आँसू"), ("sweat", "पसीना"),
    ],
    "animals": [
        ("cow", "गाय"), ("buffalo", "भैंस"), ("goat", "बकरी"), ("sheep", "भेड़"), ("horse", "घोड़ा"),
        ("donkey", "गधा"), ("mule", "खच्चर"), ("dog", "कुत्ता"), ("cat", "बिल्ली"), ("hen", "मुर्गी"),
        ("rooster", "मुर्गा"), ("egg", "अंडा"), ("bird", "चिड़िया"), ("crow", "कौआ"), ("sparrow", "गौरैया"),
        ("eagle", "चील"), ("pigeon", "कबूतर"), ("parrot", "तोता"), ("owl", "उल्लू"), ("snake", "साँप"),
        ("lizard", "छिपकली"), ("frog", "मेंढक"), ("fish", "मछली"), ("bee", "मधुमक्खी"), ("fly", "मक्खी"),
        ("mosquito", "मच्छर"), ("ant", "चींटी"), ("butterfly", "तितली"), ("spider", "मकड़ी"), ("monkey", "बंदर"),
        ("bear", "भालू"), ("leopard", "तेंदुआ"), ("fox", "लोमड़ी"), ("jackal", "सियार"), ("deer", "हिरण"),
        ("rabbit", "ख़रगोश"), ("rat", "चूहा"), ("wolf", "भेड़िया"), ("calf", "बछड़ा"), ("lamb", "मेमना"),
        ("kid (baby goat)", "बकरी का बच्चा"), ("ox", "बैल"), ("camel", "ऊँट"), ("peacock", "मोर"), ("cuckoo", "कोयल"),
        ("wool", "ऊन"), ("horn", "सींग"), ("tail", "पूँछ"), ("feather", "पंख"), ("nest", "घोंसला"),
    ],
    "food": [
        ("bread", "रोटी"), ("rice", "चावल"), ("lentils", "दाल"), ("wheat", "गेहूँ"), ("maize", "मक्का"),
        ("flour", "आटा"), ("salt", "नमक"), ("sugar", "चीनी"), ("oil", "तेल"), ("ghee", "घी"), ("butter", "मक्खन"),
        ("milk", "दूध"), ("yogurt", "दही"), ("buttermilk", "छाछ"), ("cheese", "पनीर"), ("meat", "गोश्त"),
        ("chicken (meat)", "मुर्ग़े का गोश्त"), ("tea", "चाय"), ("water", "पानी"), ("honey", "शहद"), ("onion", "प्याज़"),
        ("garlic", "लहसुन"), ("ginger", "अदरक"), ("potato", "आलू"), ("tomato", "टमाटर"), ("spinach", "पालक"),
        ("pumpkin", "कद्दू"), ("cucumber", "खीरा"), ("chilli", "मिर्च"), ("turmeric", "हल्दी"), ("cumin", "ज़ीरा"),
        ("apple", "सेब"), ("mango", "आम"), ("banana", "केला"), ("walnut", "अखरोट"), ("almond", "बादाम"),
        ("grapes", "अंगूर"), ("pomegranate", "अनार"), ("apricot", "ख़ुबानी"), ("pear", "नाशपाती"), ("lemon", "नींबू"),
        ("orange (fruit)", "संतरा"), ("radish", "मूली"), ("carrot", "गाजर"), ("peas", "मटर"), ("beans", "सेम"),
        ("mustard greens", "सरसों का साग"), ("breakfast", "नाश्ता"), ("lunch", "दोपहर का खाना"), ("dinner", "रात का खाना"),
        ("sweets", "मिठाई"), ("jaggery", "गुड़"), ("pickle", "अचार"), ("curry", "सालन"), ("porridge", "दलिया"),
        ("corn bread", "मक्की की रोटी"), ("dried fruit", "सूखे मेवे"), ("bone broth", "यख़नी"),
    ],
    "nature": [
        ("sun", "सूरज"), ("moon", "चाँद"), ("star", "तारा"), ("sky", "आसमान"), ("cloud", "बादल"), ("rain", "बारिश"),
        ("snow", "बर्फ़"), ("ice", "बर्फ़ (जमी हुई)"), ("wind", "हवा"), ("storm", "तूफ़ान"), ("lightning", "बिजली (आसमानी)"),
        ("fog", "कोहरा"), ("mountain", "पहाड़"), ("hill", "पहाड़ी"), ("valley", "घाटी"), ("river", "नदी"),
        ("stream", "नाला"), ("spring (water source)", "झरना"), ("lake", "झील"), ("forest", "जंगल"), ("tree", "पेड़"),
        ("leaf", "पत्ता"), ("root", "जड़"), ("branch", "डाली"), ("flower", "फूल"), ("grass", "घास"), ("stone", "पत्थर"),
        ("sand", "रेत"), ("soil", "मिट्टी"), ("mud", "कीचड़"), ("dust", "धूल"), ("fire", "आग"), ("smoke", "धुआँ"),
        ("footpath", "पगडंडी"), ("field", "खेत"), ("cave", "गुफ़ा"), ("pine tree", "चीड़ का पेड़"), ("deodar tree", "देवदार"),
        ("shade", "छाया"), ("earthquake", "भूकंप"), ("landslide", "भूस्खलन"), ("flood", "बाढ़"), ("rainbow", "इंद्रधनुष"),
        ("hail", "ओले"), ("frost", "पाला"), ("meadow", "चरागाह"), ("glacier", "हिमनद"), ("waterfall", "आबशार"),
        ("thorn", "काँटा"), ("seed", "बीज"), ("wood", "लकड़ी"), ("bark (of tree)", "छाल"), ("walnut tree", "अखरोट का पेड़"),
    ],
    "household": [
        ("house", "घर"), ("room", "कमरा"), ("door", "दरवाज़ा"), ("window", "खिड़की"), ("roof", "छत"), ("wall", "दीवार"),
        ("floor", "फ़र्श"), ("stairs", "सीढ़ियाँ"), ("courtyard", "आँगन"), ("kitchen", "रसोई"), ("stove", "चूल्हा"),
        ("pot", "बर्तन"), ("plate", "थाली"), ("cup", "प्याला"), ("glass", "गिलास"), ("spoon", "चम्मच"), ("knife", "चाकू"),
        ("bed", "बिस्तर"), ("pillow", "तकिया"), ("blanket", "कंबल"), ("quilt", "रज़ाई"), ("mat", "चटाई"),
        ("oil lamp", "दीया"), ("broom", "झाड़ू"), ("bucket", "बाल्टी"), ("rope", "रस्सी"), ("basket", "टोकरी"),
        ("box", "डिब्बा"), ("mirror", "आईना"), ("comb", "कंघी"), ("soap", "साबुन"), ("needle", "सुई"), ("thread", "धागा"),
        ("key", "चाबी"), ("lock", "ताला"), ("firewood", "जलाने की लकड़ी"), ("clay water pot", "घड़ा"), ("cradle", "पालना"),
        ("chair", "कुर्सी"), ("table", "मेज़"), ("shelf", "ताक"), ("candle", "मोमबत्ती"), ("matchbox", "माचिस"),
        ("griddle (for bread)", "तवा"), ("rolling pin", "बेलन"), ("ladle", "करछी"), ("sieve", "छलनी"), ("churn", "मथनी"),
        ("hookah", "हुक़्क़ा"), ("bag", "थैला"),
    ],
    "clothing": [
        ("shirt", "क़मीज़"), ("trousers", "पतलून"), ("shawl", "शॉल"), ("cap", "टोपी"), ("turban", "पगड़ी"),
        ("scarf (dupatta)", "दुपट्टा"), ("shoes", "जूते"), ("socks", "मोज़े"), ("coat", "कोट"), ("sweater", "स्वेटर"),
        ("dress", "पोशाक"), ("belt", "बेल्ट"), ("ring", "अँगूठी"), ("bangle", "चूड़ी"), ("earring", "बाली"),
        ("necklace", "हार"), ("cloth", "कपड़ा"), ("button", "बटन"), ("pocket", "जेब"), ("sandals", "चप्पल"),
        ("woollen coat", "ऊनी कोट"), ("veil", "घूँघट"), ("embroidery", "कढ़ाई"), ("nose ring", "नथ"),
    ],
    "colours": [
        ("red", "लाल"), ("blue", "नीला"), ("green", "हरा"), ("yellow", "पीला"), ("white", "सफ़ेद"), ("black", "काला"),
        ("brown", "भूरा"), ("grey", "स्लेटी"), ("pink", "गुलाबी"), ("orange (colour)", "नारंगी"), ("purple", "बैंगनी"),
        ("golden", "सुनहरा"), ("silver (colour)", "चाँदी जैसा"), ("dark", "गहरा रंग"), ("light (colour)", "हल्का रंग"),
    ],
    "numbers": [
        ("one", "एक"), ("two", "दो"), ("three", "तीन"), ("four", "चार"), ("five", "पाँच"), ("six", "छह"),
        ("seven", "सात"), ("eight", "आठ"), ("nine", "नौ"), ("ten", "दस"), ("eleven", "ग्यारह"), ("twelve", "बारह"),
        ("thirteen", "तेरह"), ("fourteen", "चौदह"), ("fifteen", "पंद्रह"), ("sixteen", "सोलह"), ("seventeen", "सत्रह"),
        ("eighteen", "अठारह"), ("nineteen", "उन्नीस"), ("twenty", "बीस"), ("twenty-five", "पच्चीस"), ("thirty", "तीस"),
        ("forty", "चालीस"), ("fifty", "पचास"), ("sixty", "साठ"), ("seventy", "सत्तर"), ("eighty", "अस्सी"),
        ("ninety", "नब्बे"), ("hundred", "सौ"), ("thousand", "हज़ार"), ("half", "आधा"), ("quarter", "चौथाई"),
        ("one and a half", "डेढ़"), ("two and a half", "ढाई"), ("first", "पहला"), ("second", "दूसरा"), ("third", "तीसरा"),
        ("last", "आख़िरी"), ("many", "बहुत सारे"), ("few", "थोड़े"), ("all", "सब"), ("nothing", "कुछ नहीं"),
    ],
    "time": [
        ("today", "आज"), ("tomorrow", "कल (आने वाला)"), ("yesterday", "कल (बीता हुआ)"), ("day after tomorrow", "परसों"),
        ("morning", "सुबह"), ("afternoon", "दोपहर"), ("evening", "शाम"), ("night", "रात"), ("midnight", "आधी रात"),
        ("dawn", "भोर"), ("day", "दिन"), ("week", "हफ़्ता"), ("month", "महीना"), ("year", "साल"), ("hour", "घंटा"),
        ("minute", "मिनट"), ("now", "अभी"), ("later", "बाद में"), ("always", "हमेशा"), ("never", "कभी नहीं"),
        ("sometimes", "कभी-कभी"), ("early", "जल्दी"), ("late", "देर"), ("Monday", "सोमवार"), ("Tuesday", "मंगलवार"),
        ("Wednesday", "बुधवार"), ("Thursday", "गुरुवार"), ("Friday", "शुक्रवार"), ("Saturday", "शनिवार"), ("Sunday", "रविवार"),
        ("spring (season)", "वसंत"), ("summer", "गर्मी का मौसम"), ("autumn", "पतझड़"), ("winter", "सर्दी का मौसम"),
        ("monsoon", "बरसात"), ("noon", "दोपहर के बारह बजे"), ("sunset", "सूर्यास्त"), ("sunrise", "सूर्योदय"),
    ],
    "verbs": [
        ("to eat", "खाना"), ("to drink", "पीना"), ("to sleep", "सोना"), ("to wake up", "जागना"), ("to walk", "चलना"),
        ("to run", "दौड़ना"), ("to sit", "बैठना"), ("to stand", "खड़ा होना"), ("to come", "आना"), ("to go", "जाना"),
        ("to see", "देखना"), ("to hear", "सुनना"), ("to speak", "बोलना"), ("to say", "कहना"), ("to ask", "पूछना"),
        ("to give", "देना"), ("to take", "लेना"), ("to bring", "लाना"), ("to lift", "उठाना"), ("to buy", "ख़रीदना"),
        ("to sell", "बेचना"), ("to cook", "पकाना"), ("to wash", "धोना"), ("to cut", "काटना"), ("to sow", "बोना"),
        ("to harvest", "फ़सल काटना"), ("to plough", "हल चलाना"), ("to graze (animals)", "चराना"), ("to milk", "दूध निकालना"),
        ("to read", "पढ़ना"), ("to write", "लिखना"), ("to learn", "सीखना"), ("to teach", "सिखाना"), ("to work", "काम करना"),
        ("to play", "खेलना"), ("to sing", "गाना"), ("to dance", "नाचना"), ("to laugh", "हँसना"), ("to cry", "रोना"),
        ("to love", "प्यार करना"), ("to fear", "डरना"), ("to fight", "लड़ना"), ("to think", "सोचना"), ("to remember", "याद करना"),
        ("to forget", "भूलना"), ("to know", "जानना"), ("to want", "चाहना"), ("to open", "खोलना"), ("to close", "बंद करना"),
        ("to build", "बनाना"), ("to break", "तोड़ना"), ("to fall", "गिरना"), ("to climb", "चढ़ना"), ("to swim", "तैरना"),
        ("to fly", "उड़ना"), ("to die", "मरना"), ("to be born", "पैदा होना"), ("to marry", "शादी करना"), ("to wait", "इंतज़ार करना"),
        ("to search", "ढूँढना"), ("to find", "पाना"), ("to lose", "खोना"), ("to hit", "मारना"), ("to pull", "खींचना"),
        ("to push", "धकेलना"), ("to throw", "फेंकना"), ("to catch", "पकड़ना"), ("to sew", "सिलना"), ("to burn", "जलाना"),
        ("to light the fire", "आग जलाना"), ("to pray", "दुआ करना"), ("to sweep", "झाड़ू लगाना"), ("to knead dough", "आटा गूँधना"),
        ("to carry on the head", "सिर पर उठाना"), ("to spin wool", "ऊन कातना"), ("to weave", "बुनना"), ("to dig", "खोदना"),
        ("to bathe", "नहाना"), ("to wear", "पहनना"), ("to send", "भेजना"), ("to receive", "पाना (मिलना)"), ("to count", "गिनना"),
        ("to shout", "चिल्लाना"), ("to whisper", "फुसफुसाना"), ("to smile", "मुस्कुराना"), ("to hide", "छिपना"), ("to steal", "चुराना"),
        ("to help", "मदद करना"), ("to rest", "आराम करना"), ("to return", "लौटना"), ("to arrive", "पहुँचना"), ("to leave", "निकलना"),
    ],
    "adjectives": [
        ("big", "बड़ा"), ("small", "छोटा"), ("tall", "लंबा"), ("short (height)", "नाटा"), ("hot", "गर्म"), ("cold", "ठंडा"),
        ("new", "नया"), ("old (thing)", "पुराना"), ("old (person)", "बूढ़ा"), ("good", "अच्छा"), ("bad", "बुरा"),
        ("beautiful", "सुंदर"), ("ugly", "बदसूरत"), ("fast", "तेज़"), ("slow", "धीमा"), ("heavy", "भारी"),
        ("light (weight)", "हल्का"), ("strong", "मज़बूत"), ("weak", "कमज़ोर"), ("rich", "अमीर"), ("poor", "ग़रीब"),
        ("clean", "साफ़"), ("dirty", "गंदा"), ("wet", "गीला"), ("dry", "सूखा"), ("sweet", "मीठा"), ("sour", "खट्टा"),
        ("bitter", "कड़वा"), ("salty", "नमकीन"), ("spicy", "तीखा"), ("full", "भरा हुआ"), ("empty", "ख़ाली"),
        ("near", "पास"), ("far", "दूर"), ("high", "ऊँचा"), ("low", "नीचा"), ("deep", "गहरा"), ("thick", "मोटा"),
        ("thin", "पतला"), ("soft", "नरम"), ("hard", "सख़्त"), ("loud", "ऊँची आवाज़ वाला"), ("quiet", "शांत"),
        ("happy", "ख़ुश"), ("sad", "उदास"), ("angry", "ग़ुस्से में"), ("tired", "थका हुआ"), ("hungry", "भूखा"),
        ("thirsty", "प्यासा"), ("sick", "बीमार"), ("healthy", "स्वस्थ"), ("young", "जवान"), ("true", "सच"),
        ("false", "झूठ"), ("easy", "आसान"), ("difficult", "मुश्किल"), ("cheap", "सस्ता"), ("expensive", "महँगा"),
        ("blind", "अंधा"), ("deaf", "बहरा"), ("lame", "लँगड़ा"), ("brave", "बहादुर"), ("lazy", "आलसी"),
        ("clever", "चालाक"), ("foolish", "मूर्ख"), ("kind", "दयालु"), ("honest", "ईमानदार"), ("wide", "चौड़ा"),
        ("narrow", "सँकरा"), ("round", "गोल"), ("sharp", "तेज़ धार वाला"), ("ripe", "पका हुआ"), ("raw", "कच्चा"),
        ("alone", "अकेला"), ("together", "साथ"), ("same", "एक जैसा"), ("different", "अलग"), ("open", "खुला"),
        ("closed", "बंद"), ("right (side)", "दायाँ"), ("left (side)", "बायाँ"), ("inside", "अंदर"), ("outside", "बाहर"),
    ],
    "people_places": [
        ("farmer", "किसान"), ("shepherd", "चरवाहा"), ("teacher", "शिक्षक"), ("doctor", "डॉक्टर"), ("shopkeeper", "दुकानदार"),
        ("driver", "ड्राइवर"), ("carpenter", "बढ़ई"), ("blacksmith", "लोहार"), ("tailor", "दर्ज़ी"), ("barber", "नाई"),
        ("potter", "कुम्हार"), ("weaver", "बुनकर"), ("cook", "रसोइया"), ("soldier", "सिपाही"), ("priest", "पुजारी"),
        ("imam", "इमाम"), ("singer", "गायक"), ("student", "छात्र"), ("labourer", "मज़दूर"), ("village", "गाँव"),
        ("city", "शहर"), ("market", "बाज़ार"), ("school", "स्कूल"), ("hospital", "अस्पताल"), ("mosque", "मस्जिद"),
        ("temple", "मंदिर"), ("shop", "दुकान"), ("road", "सड़क"), ("bridge", "पुल"), ("well", "कुआँ"),
        ("bus stop", "बस अड्डा"), ("graveyard", "क़ब्रिस्तान"), ("office", "दफ़्तर"), ("bank", "बैंक"), ("post office", "डाकघर"),
        ("police station", "थाना"), ("mill", "चक्की"), ("shrine", "दरगाह"), ("border", "सरहद"), ("headman", "नंबरदार"),
        ("thief", "चोर"), ("king", "राजा"), ("queen", "रानी"), ("saint", "पीर"), ("stranger", "अजनबी"),
        ("nomad", "ख़ानाबदोश"), ("milkman", "दूधवाला"), ("mason", "राजमिस्त्री"), ("midwife", "दाई"), ("hunter", "शिकारी"),
    ],
    "tools_farming": [
        ("plough", "हल"), ("sickle", "दराँती"), ("axe", "कुल्हाड़ी"), ("hoe", "कुदाल"), ("spade", "फावड़ा"),
        ("hammer", "हथौड़ा"), ("crop", "फ़सल"), ("harvest", "कटाई"), ("hay", "सूखी घास"), ("fodder", "चारा"),
        ("manure", "खाद"), ("irrigation channel", "सिंचाई की नाली"), ("terraced field", "सीढ़ीदार खेत"), ("orchard", "बाग़"),
        ("threshing floor", "खलिहान"), ("cattle shed", "गौशाला"), ("stick", "लाठी"), ("sack", "बोरी"),
        ("weighing scale", "तराज़ू"), ("wheel", "पहिया"), ("cart", "गाड़ी"), ("bus", "बस"), ("bicycle", "साइकिल"),
        ("tractor", "ट्रैक्टर"), ("boat", "नाव"), ("saddle", "काठी"), ("bell (for animals)", "घंटी"), ("yoke", "जुआ"),
        ("millstone", "चक्की का पाट"), ("ladder", "सीढ़ी"), ("nail (metal)", "कील"), ("saw", "आरी"), ("fence", "बाड़"),
        ("gate", "फाटक"), ("tent", "तंबू"), ("walking stick", "छड़ी"), ("gun", "बंदूक"), ("spinning wheel", "चरखा"),
    ],
    "abstract": [
        ("love", "प्यार"), ("fear", "डर"), ("anger", "ग़ुस्सा"), ("joy", "ख़ुशी"), ("sorrow", "दुख"), ("shame", "शर्म"),
        ("hope", "उम्मीद"), ("pain", "दर्द"), ("dream", "सपना"), ("song", "गीत"), ("story", "कहानी"), ("word", "शब्द"),
        ("language", "भाषा"), ("name", "नाम"), ("truth", "सच्चाई"), ("lie", "झूठ"), ("God", "ख़ुदा"), ("prayer", "दुआ"),
        ("luck", "क़िस्मत"), ("life", "ज़िंदगी"), ("death", "मौत"), ("money", "पैसा"), ("gift", "तोहफ़ा"), ("wedding", "शादी"),
        ("festival", "त्योहार"), ("fair", "मेला"), ("game", "खेल"), ("work", "काम"), ("question", "सवाल"), ("answer", "जवाब"),
        ("letter", "चिट्ठी"), ("news", "ख़बर"), ("voice", "आवाज़"), ("silence", "ख़ामोशी"), ("peace", "अमन"),
        ("war", "जंग"), ("promise", "वादा"), ("secret", "राज़"), ("memory", "याद"), ("habit", "आदत"),
        ("respect", "इज़्ज़त"), ("trouble", "मुसीबत"), ("help", "मदद"), ("health", "सेहत"), ("sleep", "नींद"),
        ("hunger", "भूख"), ("thirst", "प्यास"), ("age", "उम्र"), ("strength", "ताक़त"), ("wisdom", "अक़्ल"),
    ],
}

# ================================================================ translate: templates
# Slot items are chosen so the Hindi stays grammatical regardless of the noun's gender.

_NEED = [
    ("water", "पानी"), ("bread", "रोटी"), ("milk", "दूध"), ("salt", "नमक"), ("tea", "चाय"), ("rice", "चावल"),
    ("sugar", "चीनी"), ("oil", "तेल"), ("a blanket", "एक कंबल"), ("a rope", "एक रस्सी"), ("firewood", "लकड़ी"),
    ("medicine", "दवा"), ("money", "पैसे"), ("a knife", "एक चाकू"), ("a bucket", "एक बाल्टी"), ("help", "मदद"),
    ("rest", "आराम"), ("new shoes", "नए जूते"), ("a shawl", "एक शॉल"), ("soap", "साबुन"), ("flour", "आटा"),
    ("matches", "माचिस"), ("a needle and thread", "सुई-धागा"), ("a lamp", "एक दीया"), ("time", "समय"),
]
_WHERE = [
    ("market", "बाज़ार"), ("school", "स्कूल"), ("hospital", "अस्पताल"), ("mosque", "मस्जिद"), ("well", "कुआँ"),
    ("bus stop", "बस अड्डा"), ("shop", "दुकान"), ("bridge", "पुल"), ("river", "नदी"), ("road", "सड़क"),
    ("kitchen", "रसोई"), ("door", "दरवाज़ा"), ("key", "चाबी"), ("teacher", "शिक्षक"), ("doctor", "डॉक्टर"),
    ("cow", "गाय"), ("dog", "कुत्ता"), ("bucket", "बाल्टी"), ("knife", "चाकू"), ("lamp", "दीया"),
    ("post office", "डाकघर"), ("toilet", "शौचालय"), ("path", "रास्ता"), ("spring", "झरना"), ("graveyard", "क़ब्रिस्तान"),
]
_GIVE = [
    ("the knife", "चाकू"), ("the bucket", "बाल्टी"), ("the rope", "रस्सी"), ("the salt", "नमक"), ("the bread", "रोटी"),
    ("the cup", "प्याला"), ("the plate", "थाली"), ("the spoon", "चम्मच"), ("the basket", "टोकरी"), ("the key", "चाबी"),
    ("the blanket", "कंबल"), ("the stick", "लाठी"), ("the axe", "कुल्हाड़ी"), ("the sickle", "दराँती"), ("the book", "किताब"),
    ("the pen", "क़लम"), ("the phone", "फ़ोन"), ("the money", "पैसे"), ("the shawl", "शॉल"), ("the box", "डिब्बा"),
]
_HAVE = [
    ("milk", "दूध"), ("eggs", "अंडे"), ("fresh bread", "ताज़ा रोटी"), ("a phone", "फ़ोन"), ("a car", "गाड़ी"),
    ("a cow", "गाय"), ("goats", "बकरियाँ"), ("land", "ज़मीन"), ("a radio", "रेडियो"), ("a torch", "टॉर्च"),
    ("sugar", "चीनी"), ("medicine", "दवा"), ("time", "समय"), ("children", "बच्चे"), ("brothers", "भाई"),
    ("a bicycle", "साइकिल"), ("walnuts", "अखरोट"), ("apples", "सेब"), ("wool", "ऊन"), ("a horse", "घोड़ा"),
]
_PRICE = [
    ("rice", "चावल"), ("wheat", "गेहूँ"), ("sugar", "चीनी"), ("tea", "चाय"), ("oil", "तेल"), ("onions", "प्याज़"),
    ("potatoes", "आलू"), ("tomatoes", "टमाटर"), ("apples", "सेब"), ("walnuts", "अखरोट"), ("milk", "दूध"),
    ("ghee", "घी"), ("meat", "गोश्त"), ("a goat", "एक बकरी"), ("a shawl", "एक शॉल"), ("shoes", "जूतों"),
    ("firewood", "लकड़ी"), ("salt", "नमक"), ("eggs", "अंडों"), ("a blanket", "एक कंबल"),
]
_CALL = [
    ("the doctor", "डॉक्टर"), ("the teacher", "शिक्षक"), ("the children", "बच्चों"), ("your father", "अपने पिता"),
    ("your mother", "अपनी माँ"), ("the neighbour", "पड़ोसी"), ("the shepherd", "चरवाहे"), ("the driver", "ड्राइवर"),
    ("the shopkeeper", "दुकानदार"), ("the barber", "नाई"), ("the carpenter", "बढ़ई"), ("the imam", "इमाम"),
    ("grandmother", "दादी"), ("grandfather", "दादा"), ("your brother", "अपने भाई"), ("your sister", "अपनी बहन"),
    ("the headman", "नंबरदार"), ("the midwife", "दाई"), ("everyone", "सबको"), ("the guests", "मेहमानों"),
]
_WENT = [
    ("market", "बाज़ार"), ("city", "शहर"), ("hospital", "अस्पताल"), ("school", "स्कूल"), ("wedding", "शादी में"),
    ("fair", "मेले में"), ("forest", "जंगल"), ("fields", "खेतों में"), ("river", "नदी पर"), ("mosque", "मस्जिद"),
    ("shrine", "दरगाह"), ("mountains", "पहाड़ों पर"), ("doctor", "डॉक्टर के पास"), ("neighbour's house", "पड़ोसी के घर"),
    ("spring", "झरने पर"), ("graveyard", "क़ब्रिस्तान"),
]

TEMPLATES: list[tuple[str, str, str, list[tuple[str, str]]]] = [
    ("needs", "I need {en}.", "मुझे {hi} चाहिए।", _NEED),
    ("directions", "Where is the {en}?", "{hi} कहाँ है?", _WHERE),
    ("everyday", "Give me {en}.", "मुझे {hi} दो।", _GIVE),
    ("market", "Do you have {en}?", "क्या आपके पास {hi} है?", _HAVE),
    ("market", "What is the price of {en}?", "{hi} का क्या भाव है?", _PRICE),
    ("everyday", "Call {en}.", "{hi} को बुलाओ।", _CALL),
    ("travel", "We went to the {en}.", "हम {hi} गए थे।", _WENT),
]


# ================================================================================ build


def _translate(category: str, en: str, hi: str) -> PromptSpec:
    return PromptSpec(category, "translate", f"How do you say: \u201c{en}\u201d", f"अपनी भाषा में कहिए: \u201c{hi}\u201d")


def _word(category: str, en: str, hi: str) -> PromptSpec:
    return PromptSpec(category, "word", f"What do you call \u2018{en}\u2019 in your language?", f"आपकी भाषा में \u2018{hi}\u2019 को क्या कहते हैं?")


def _dedupe(specs: Iterable[PromptSpec]) -> list[PromptSpec]:
    seen: set[str] = set()
    out: list[PromptSpec] = []
    for s in specs:
        k = s.en.strip().lower()
        if k in seen:
            continue
        seen.add(k)
        out.append(s)
    return out


def build_bank() -> list[PromptSpec]:
    specs: list[PromptSpec] = []
    specs += [PromptSpec(c, "question", en, hi) for c, en, hi in QUESTIONS]
    specs += [_translate(c, en, hi) for c, en, hi in SENTENCES]
    for category, en_t, hi_t, items in TEMPLATES:
        specs += [_translate(category, en_t.format(en=en), hi_t.format(hi=hi)) for en, hi in items]
    for category, items in WORDS.items():
        specs += [_word(category, en, hi) for en, hi in items]
    return _dedupe(specs)


CATEGORY_LABELS: dict[str, tuple[str, str]] = {
    # category -> (English label, Hindi label) for the UI
    "greetings": ("Greetings", "अभिवादन"),
    "family": ("Family", "परिवार"),
    "home": ("Home", "घर"),
    "food": ("Food", "खाना"),
    "daily_life": ("Daily life", "रोज़मर्रा"),
    "village": ("Village", "गाँव"),
    "farming": ("Farming", "खेती"),
    "animals": ("Animals", "जानवर"),
    "weather": ("Weather", "मौसम"),
    "festivals": ("Festivals", "त्योहार"),
    "childhood": ("Childhood", "बचपन"),
    "work": ("Work", "काम"),
    "travel": ("Travel", "सफ़र"),
    "health": ("Health", "सेहत"),
    "nature": ("Nature", "प्रकृति"),
    "stories": ("Stories", "कहानियाँ"),
    "opinions": ("Opinions", "राय"),
    "language": ("Language", "भाषा"),
    "market": ("Market", "बाज़ार"),
    "school": ("School", "स्कूल"),
    "everyday": ("Everyday phrases", "रोज़ के वाक्य"),
    "feelings": ("Feelings", "भावनाएँ"),
    "time": ("Time", "समय"),
    "directions": ("Directions", "रास्ता"),
    "needs": ("Needs", "ज़रूरतें"),
    "body": ("Body", "शरीर"),
    "household": ("Household", "घर का सामान"),
    "clothing": ("Clothing", "कपड़े"),
    "colours": ("Colours", "रंग"),
    "numbers": ("Numbers", "गिनती"),
    "verbs": ("Actions", "क्रियाएँ"),
    "adjectives": ("Describing words", "विशेषण"),
    "people_places": ("People and places", "लोग और जगहें"),
    "tools_farming": ("Tools", "औज़ार"),
    "abstract": ("Ideas and feelings", "विचार"),
}
